### ISSUE TITLE
Should improve build process

### ISSUE THREAD

**Issue by dfahlander** [ignasbernotas/dexie-relationships#5]
Should try buble + rollup instead of babel + webpack.
An alternative would be keeping babel but replace webpack with webpack2-beta.

If we do this we will have better outputs with smaller footprints in the dist folder, such as:

* dexie-relationships.js
* dexie-relationships.min.js
* dexie-relationships.es.js

We would also support stuff like `watch` without having to develop a build system like I had to in Dexie.

**Comment by rmtuckerphx** [comment]
Is there a way to include dexie-relationships using a script tag like how I am able to with dexie? Does this project support use outside of WebPack?

**Comment by ignasbernotas** [comment]
Hi,

With 1.2.0 I have replace Webpack+Babel with Rollup+Buble. The distributable files now should work in any environment. I've tested it in node and chrome. Please let me know how you get on. Thanks!
